linters:
  enable:
    - gofmt
    - govet
    - gosec
    - gosimple
    - staticcheck
    - unused
    - revive
    - errcheck
    - goimports
    - misspell
    - dupl
    - whitespace

linters-settings:
  gosec:
    severity: "medium"
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G404: Use of weak random number generator"
  exclude-dirs:
    - pkg/grpc

run:
  concurrency: 4
  timeout: 5m