version: '3.8'

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - pg
    environment:
      - GRPC_PORT=50051
      - KUCOIN_BASE_URL=https://api.kucoin.com
      - LOG_LEVEL=INFO
      - DB_HOST=pg
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=disable

volumes:
  postgres_volume: