version: '3.8'

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686"  # Интерфейс Jaeger UI
      - "4317:4317"    # OTLP gRPC порт
      - "4318:4318"    # OTLP HTTP порт
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "8181:8181"  # Для метрик Prometheus
    depends_on:
      - pg
    environment:
      - GRPC_PORT=50051
      - KUCOIN_BASE_URL=https://api.kucoin.com
      - LOG_LEVEL=INFO
      - DB_HOST=pg
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=disable
      - SERVICE_NAME=rate-service
      - SERVICE_VERSION=1.0.0
      - ENVIRONMENT=development
      - ENABLE_TRACING=true
      - OTLP_ENDPOINT=jaeger:4317
      - ENABLE_METRICS=true
      - METRICS_HTTP_ADDR=0.0.0.0:8181
      - ENABLE_DEBUG_SERVER=true
      - DEBUG_SERVER_ADDR=0.0.0.0:8182
    restart: on-failure

volumes:
  postgres_volume:
  prometheus_data:
  grafana_data: